@startuml

actor "User" as user

node "PHP Login Management" {
    node "Model" as model /' Model Request '/
    node "Domain" as domain /' Representation Database Table '/
    node "Controller" as controller
    node "View" as view
    node "Service" as service
    node "Repository" as repository
}

database "Mysql" as mysql

user --> controller : 1
controller --> model : 2
controller --> service : 3
service --> repository : 4
repository --> mysql : 5
repository --> domain : 6
controller --> view : 7
controller --> user : 8



@enduml