/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.24.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.CreateOrUpdateTodolist;
import org.springframework.lang.Nullable;
import org.openapitools.model.Todolist;
import org.openapitools.model.TodolistTodolistIdDelete200Response;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-08-22T10:24:41.631048908+07:00[Asia/Jakarta]", comments = "Generator version: 7.24.0")
@Validated
@Tag(name = "Todolist", description = "the Todolist API")
public interface TodolistApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    String PATH_TODOLIST_GET = "/todolist";
    /**
     * GET /todolist : Get all todolist
     * Get all active todolist by default
     *
     * @param includeCompleted Include completed todolist in result (optional, default to false)
     * @param name Filter todolist by name (optional)
     * @return Success get all todolist (status code 200)
     */
    @Operation(
        operationId = "todolistGet",
        summary = "Get all todolist",
        description = "Get all active todolist by default",
        tags = { "Todolist" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success get all todolist", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Todolist.class)), examples = {
                    @ExampleObject(
                        name = "",
                        value = "[{\"id\":\"1\",\"name\":\"Java\",\"priority\":1,\"tags\":[\"java\",\"spring\"]},{\"id\":\"2\",\"name\":\"PHP\",\"priority\":2,\"tags\":[\"php\",\"laravel\"]}]"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "todolist_auth")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = TodolistApi.PATH_TODOLIST_GET,
        produces = { "application/json" }
    )
    default ResponseEntity<List<Todolist>> todolistGet(
        @Parameter(name = "include_completed", description = "Include completed todolist in result", in = ParameterIn.QUERY) @Valid @RequestParam(value = "include_completed", required = false, defaultValue = "false") Boolean includeCompleted,
        @Size(min = 1, max = 255) @Parameter(name = "name", description = "Filter todolist by name", in = ParameterIn.QUERY) @Valid @RequestParam(value = "name", required = false) @Nullable String name
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"id\" : \"id\", \"name\" : \"name\", \"priority\" : 0.8008281904610115, \"tags\" : [ \"tags\", \"tags\" ] }, { \"id\" : \"id\", \"name\" : \"name\", \"priority\" : 0.8008281904610115, \"tags\" : [ \"tags\", \"tags\" ] } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_TODOLIST_POST = "/todolist";
    /**
     * POST /todolist : Create a new todolist
     * Create a new todolist to database
     *
     * @param createOrUpdateTodolist  (required)
     * @return Success create todolist (status code 200)
     */
    @Operation(
        operationId = "todolistPost",
        summary = "Create a new todolist",
        description = "Create a new todolist to database",
        tags = { "Todolist" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success create todolist", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Todolist.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"id\":\"1\",\"name\":\"Java\",\"priority\":1,\"tags\":[\"java\",\"spring\"]}"
                    ),
                    @ExampleObject(
                        name = "",
                        value = "{\"id\":\"2\",\"name\":\"PHP\",\"priority\":2,\"tags\":[\"php\",\"laravel\"]}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "todolist_auth")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = TodolistApi.PATH_TODOLIST_POST,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Todolist> todolistPost(
        @Parameter(name = "CreateOrUpdateTodolist", description = "", required = true) @Valid @RequestBody CreateOrUpdateTodolist createOrUpdateTodolist
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : \"id\", \"name\" : \"name\", \"priority\" : 0.8008281904610115, \"tags\" : [ \"tags\", \"tags\" ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_TODOLIST_TODOLIST_ID_DELETE = "/todolist/{todolistId}";
    /**
     * DELETE /todolist/{todolistId} : Delete existing todolist
     * Delete existing todolist in database
     *
     * @param todolistId The id of the todolist to update (required)
     * @return Success delete todolist (status code 200)
     *         or Failed delete todolist, not found todolist (status code 404)
     */
    @Operation(
        operationId = "todolistTodolistIdDelete",
        summary = "Delete existing todolist",
        description = "Delete existing todolist in database",
        tags = { "Todolist" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success delete todolist", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TodolistTodolistIdDelete200Response.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"success\":true}"
                    )
                })

            }),
            @ApiResponse(responseCode = "404", description = "Failed delete todolist, not found todolist", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TodolistTodolistIdDelete200Response.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"success\":false}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "todolist_auth")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = TodolistApi.PATH_TODOLIST_TODOLIST_ID_DELETE,
        produces = { "application/json" }
    )
    default ResponseEntity<TodolistTodolistIdDelete200Response> todolistTodolistIdDelete(
        @Size(min = 1) @Parameter(name = "todolistId", description = "The id of the todolist to update", required = true, in = ParameterIn.PATH) @PathVariable("todolistId") String todolistId
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"success\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    String PATH_TODOLIST_TODOLIST_ID_PUT = "/todolist/{todolistId}";
    /**
     * PUT /todolist/{todolistId} : Update existing todolist
     * Update existing todolist in database
     *
     * @param todolistId The id of the todolist to update (required)
     * @param createOrUpdateTodolist  (required)
     * @return Success update todolist (status code 200)
     */
    @Operation(
        operationId = "todolistTodolistIdPut",
        summary = "Update existing todolist",
        description = "Update existing todolist in database",
        tags = { "Todolist" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Success update todolist", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Todolist.class), examples = {
                    @ExampleObject(
                        name = "",
                        value = "{\"id\":\"1\",\"name\":\"Java\",\"priority\":1,\"tags\":[\"java\",\"spring\"]}"
                    ),
                    @ExampleObject(
                        name = "",
                        value = "{\"id\":\"2\",\"name\":\"PHP\",\"priority\":2,\"tags\":[\"php\",\"laravel\"]}"
                    )
                })

            })
        },
        security = {
            @SecurityRequirement(name = "todolist_auth")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = TodolistApi.PATH_TODOLIST_TODOLIST_ID_PUT,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Todolist> todolistTodolistIdPut(
        @Size(min = 1) @Parameter(name = "todolistId", description = "The id of the todolist to update", required = true, in = ParameterIn.PATH) @PathVariable("todolistId") String todolistId,
        @Parameter(name = "CreateOrUpdateTodolist", description = "", required = true) @Valid @RequestBody CreateOrUpdateTodolist createOrUpdateTodolist
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : \"id\", \"name\" : \"name\", \"priority\" : 0.8008281904610115, \"tags\" : [ \"tags\", \"tags\" ] }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
