#ApplicationProperties.java
application.name=${APPLICATION_NAME:belajar-spring-config-properties}
application.version=${APPLICATION_VERSION:1.0.0}
application.production-mode=${APPLICATION_PRODUCTION_MODE:false}

#Duration
#Converter
application.default-timeout=10s
#Custom Converter
application.expire-date=2026-01-01

#DatabaseProperties.java
application.database.username=root
application.database.password=secret
application.database.database=belajar
application.database.url=jdbc:mysql://localhost:3306/belajar

#One line
#application.database.whitelist-tables=products,customers,categories

#Multiple line, can also add another by adding comma inside each index
application.database.whitelist-tables[0]=products
application.database.whitelist-tables[1]=customers
application.database.whitelist-tables[2]=categories

application.database.max-tables-size.products=100
application.database.max-tables-size.customers=100
application.database.max-tables-size.categories=100

#Role.java
#Data List
application.role.default-roles[0].id=default
application.role.default-roles[0].name=Default Role
application.role.default-roles[1].id=guest
application.role.default-roles[1].name=Guest Role

#Data Map
application.role.roles.admin.id=admin
application.role.roles.admin.name=Admin Role
application.role.roles.finance.id=finance
application.role.roles.finance.name=Finance Role

spring.profiles.active=local
profile.default=Default