services:
  web:
    build: .
    ports:
      - "80"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - basdat-network

  nginx-lb:
    image: nginx:latest
    container_name: basdat-lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - basdat-network

  db:
    image: mysql:8.0
    container_name: basdat-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: plm987!
      MYSQL_DATABASE: basdat_app_test
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - basdat-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: basdat-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - basdat-network

volumes:
  db-data:

networks:
  basdat-network:
    driver: bridge